# Generated by Django 5.2 on 2025-07-21 01:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='created_by',
            field=models.ForeignKey(default=1, help_text='Doctor who created this patient record', on_delete=django.db.models.deletion.CASCADE, related_name='created_patients', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='profile_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for patient profile image', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='xray_image_url',
            field=models.URLField(blank=True, help_text='Cloudinary URL for chest X-ray image', null=True),
        ),
    ]
