# Generated by Django 5.2 on 2025-09-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_patient_created_by_patient_profile_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='appointment_type',
            field=models.CharField(choices=[('consultation', 'Consultation'), ('follow_up', 'Follow Up'), ('checkup', 'Check Up'), ('emergency', 'Emergency'), ('screening', 'Screening')], max_length=100, verbose_name='appointment type'),
        ),
    ]
