# Generated by Django 5.2 on 2025-09-19 23:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_appointment_appointment_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['-created_at'], 'verbose_name': 'Doctor', 'verbose_name_plural': 'Doctors'},
        ),
        migrations.AddField(
            model_name='doctor',
            name='avatar_url',
            field=models.URLField(blank=True, help_text="Cloudinary URL for doctor's profile picture", null=True, verbose_name='avatar URL'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultation_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='consultation fee'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='is available for appointments'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='List of languages the doctor speaks', verbose_name='languages spoken'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='license_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='medical license number'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours_end',
            field=models.TimeField(default='17:00', verbose_name='working hours end'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours_start',
            field=models.TimeField(default='09:00', verbose_name='working hours start'),
        ),
    ]
