# Generated by Django 5.2 on 2025-06-22 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xray_image', models.ImageField(upload_to='xray_uploads/')),
                ('predicted_disease', models.CharField(choices=[('cardiomegaly', 'Cardiomegaly'), ('pneumonia', 'Pneumonia'), ('tuberculosis', 'Tuberculosis'), ('pulmonary_hypertension', 'Pulmonary Hypertension')], max_length=50)),
                ('confidence_score', models.FloatField()),
                ('all_predictions', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor_confirmed', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictions', to='dashboard.patient')),
                ('reviewed_by_doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.doctor')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
