# Generated by Django 5.2 on 2025-09-14 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_predict', '0002_alter_predictionresult_all_predictions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='predictionresult',
            name='gradcam_image',
            field=models.ImageField(blank=True, null=True, upload_to='gradcam_uploads/'),
        ),
    ]
